name: Run tests 
on: 
  push:
    branches: 
      - 'main'
    pull requests:
      branches:
      - 'main'
jobs:
  tests:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: action/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
         node-version: 18.6.0
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm test   
